Self-practice for working with numpy arrays

In [ ]:
# run this first to set up
import numpy as np

Question 1: How to stack two arrays vertically?

In [ ]:
# Input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Output: Stack array a and b vertically
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

Question 2: How to swap two columns in a numpy array?

In [ ]:
# Input:
arr = np.arange(9).reshape(3,3)

# Output: Swap columns 1 and 2 in the array arr.

Question 3: How to rank items in an array?

In [ ]:
# Input:
np.random.seed(19)
arr = np.random.randint(100, size=10)

# Output: sort the array in increasing order, output the sorted index [3, 9, 6, 2, 4, 8, 7, 5, 0, 1]

Question 4: How to find the maximum value in each row of a 2D numpy array?

In [ ]:
# Input: 
np.random.seed(17)
arr = np.random.randint(1,10, [5,3])

# Output: Compute the maximum value of each row in the array arr. Flatten the resut as a 1D numpy array.

Question 5: Slice a 2D numpy array

In [ ]:
# Input:
arr = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

# Output: Slice the array arr to get the following result
# [[17 18]
#  [22 23]
#  [27 28]]

Question 6: Transpose and dot product

In [ ]:
# Input:
a = np.array([[1, 0], [0, 1], [4, 7]])
b = np.array([[4, 1], [2, 2], [49, 17]])

# Output: compute the dot product of the transpose of a and b

Question 7: Element-wise product

In [ ]:
# Input: 
a = np.array([[1, 0], [0, 1], [4, 7]])
b = np.array([[4, 1], [2, 2], [49, 17]])

# Output: compute the element-wise product of a and b

Question 8: Assign values to an array

In [ ]:
# Input:
np.random.seed(17)
x = np.arange(4)
arr = np.random.randint(1, 10, [10])

# Output: assign the values in array x to the last 4 elements in the array arr (in the exact same order as the elements appear in x). 
# Desired result: [2, 7, 7, 1, 7, 5, 0, 1, 2, 3]
# Note: do not use any loops to achieve this.

Follow up Question: This is a bit tricky! Take a look at the following code. 

```
x = np.arange(0, 50, 10)
x[np.array([1, 1, 3, 1])] += 1
```

What will the value of x be at the end? 

*   Option 1: [ 0, 11, 20, 31, 40]
*   Option 2: [ 0, 13, 20, 31, 40]
*   Option 3: IndexError: index is out of bounds for axis 0 with size 5
*   Option 4: I don't know!!! :(

Question 9: A challenging quesiton. Replace all None values with the mean of all elements in its row. (We will later cover this as "imputation")

*Note: you should be able to do it without using any for/while loop.*

In [ ]:
# Input:
arr = np.array([[16,  7, 23, None, 46, 23, 32, 69],
       [40, 85, 45,  None,  2, 18, 42, 57],
       [11, 99,  4, 64,  7, 92, 39, 92],
       [42, 58, None, 18, 50, 33, 62,  6],
       [39,  3, 45, 55, 14, 57, 28, None]])